#define PROGRAM 			1
#define INTEGER 			2
#define REAL 				3
#define BOOLEAN 			4
#define CHAR 				5
#define BEGIN_T 			6
#define END 				7
#define IF 					8
#define THEN 				9
#define ELSE 				10
#define DO 					11
#define WHILE 				12	
#define UNTIL 				13
#define READ 				14
#define WRITE 				15
#define INTEGER_CONSTANT	16
#define REAL_CONSTANT 		17
#define CHAR_CONSTANT 		18
#define BOOLEAN_CONSTANT	19

#define IDENTIFIER 			21
#define T_DOISP 			22
#define T_PVIRG 			23
#define T_VIRG 				24
#define T_IGUAL 			25
#define T_ABRE 				26
#define T_FECHA 			27
#define RELOP 				28
#define NOT 				29
#define ADDOP 				30
#define MENOS 				31
#define MULOP 				32

//#define DELIM				33